atividadeBDMVC/Controllers/AcademicoController.cs
using atividadeBDMVC.Data;
using atividadeBDMVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace atividadeBDMVC.Controllers
{
    public class AcademicoController : Controller
    {
        private readonly IESContext _context;

        public AcademicoController (IESContext context)
        {
            this._context = context;
        }

        /* GET: AcademicoController
        public ActionResult Index()
        {
            return View();
        }*/

        public async Task<IActionResult> Index()
        {
            return View(await _context.Academicos.OrderBy(c => c.Nome).ToListAsync());
        }

        // GET: InstituicaoController/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var academico = await _context.Academicos.SingleOrDefaultAsync(m => m.AcademicoID == id);
            if (academico == null)
            {
                return NotFound();
            }
            return View(academico);
        }

        // GET: InstituicaoController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: InstituicaoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome")] Academico academico, IFormFile img)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //parte inserida para implementar a foto
                    var stream = new MemoryStream();
                    await img.CopyToAsync(stream);
                    academico.img = stream.ToArray();
                    academico.imgType = img.ContentType;

                    if (academico.AcademicoID == null)
                    {
                        _context.Academicos.Add(academico);
                    }
                    else
                    {
                        _context.Update(academico);
                    }
                    await _context.SaveChangesAsync();


                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Não foi possível inserir os dados.");
            }
            return View(academico);
        }

        // GET: InstituicaoController/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var academico = await _context.Academicos.SingleOrDefaultAsync(m => m.AcademicoID == id);
            if (academico == null)
            {
                return NotFound();
            }
            return View(academico);
        }

        // POST: InstituicaoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long? id, [Bind("AcademicoID,Nome")] Academico
        academico, IFormFile foto)
        {
            if (id != academico.AcademicoID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    //parte inserida para implementar a foto
                    var stream = new MemoryStream();
                    await foto.CopyToAsync(stream);
                    academico.img = stream.ToArray();
                    academico.imgType = foto.ContentType;

                    if (academico.AcademicoID == null)
                    {
                        _context.Academicos.Add(academico);
                    }
                    else
                    {
                        _context.Update(academico);
                    }
                    await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await AcademicoExists(academico.AcademicoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(academico);
        }

        private async Task<bool> AcademicoExists(long? id)
        {
            return await _context.Academicos.FindAsync(id) !=null;
        }

        // GET: InstituicaoController/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var academico = await _context.Academicos.SingleOrDefaultAsync(m => m.AcademicoID == id);
            if (academico == null)
            {
                return NotFound();
            }
            return View(academico);
        }

        // POST: InstituicaoController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long? id)
        {
            var academico = await _context.Academicos.FindAsync(id);
            _context.Academicos.Remove(academico);
            await _context.SaveChangesAsync();
            TempData["Message"] = "O Academico" + academico.Nome + "Foi removido com sucesso!";
            return RedirectToAction(nameof(Index));
        }
    }
}

atividadeBDMVC/Controllers/CursoController.cs
using atividadeBDMVC.Data;
using atividadeBDMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace atividadeBDMVC.Controllers
{
    [Authorize]
    public class CursoController : Controller
    {
        // GET: CursoController
        /*public ActionResult Index()
        {
            return View();
        }*/

        private readonly IESContext _context;
        private readonly Disciplina disciplina;
        private readonly CursoDisciplinaController cursoDisciplina;

        public CursoController(IESContext context)
        {
            this._context = context;
        }

        //GET INDEX
        public async Task<ActionResult> Index()
        {
            return View(await _context.Cursos.Include(i => i.Departamento).OrderBy(c => c.Nome).ToListAsync());
        }

        // GET: CursoController/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var curso = await _context.Cursos.SingleOrDefaultAsync(m => m.CursoID == id);
            _context.Departamentos.Where(i => curso.DepartamentoID == i.DepartamentoID).Load();
            if (curso == null)
            {
                return NotFound();
            }
            return View(curso);
        }

        // GET: CursoController/Create
        public async Task<ActionResult> Create()
        {
            //var curso = _context.Cursos.Where(c => c.CursoID == cursoID).Include(cp => cp.CursoDisciplinas).First();
            var departamento = _context.Departamentos.OrderBy(i => i.Nome).ToList();
            var disciplina = _context.Disciplinas.OrderBy(i => i.Nome).ToList();
            departamento.Insert(0, new Departamento() { DepartamentoID = 0, Nome = "Selecione o Departamento" });
            ViewBag.Departamentos = departamento;
            disciplina.Insert(0, new Disciplina() { DisciplinaID = 0, Nome = "Selecione a Disciplina" });
            ViewBag.disciplina = disciplina;
            return View();
        }

        // POST: CursoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Nome", "Turno", "NumeroAlunos", "DepartamentoID")] Curso curso)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(curso);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Nào foi possivel inserir os dados solicitados");
            }
            return View(curso);
        }

        // GET: CursoController/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var curso = await _context.Cursos.SingleOrDefaultAsync(m => m.CursoID == id);
            if (curso == null)
            {
                return NotFound();
            }
            ViewBag.Departamentos = new SelectList(_context.Departamentos.OrderBy(b => b.Nome), "DepartamentoID", "Nome", curso.DepartamentoID);
            return View(curso);
        }

        // POST: CursoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(long? id, [Bind("Nome", "Turno", "NumeroAlunos", "DepartamentoID")] Curso curso)
        {
            if (id != curso.CursoID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(curso);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CursoExists(curso.CursoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Departamentos = new SelectList(_context.Departamentos.OrderBy(b => b.Nome), "DepartamentoID", "Nome", curso.DepartamentoID);
            return View(curso);
        }

        private bool CursoExists(long? id)
        {
            return _context.Cursos.Any(e => e.CursoID == id);
        }

        // GET: CursoController/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var curso = await _context.Cursos.SingleOrDefaultAsync(m => m.CursoID == id);
            if (curso == null)
            {
                return NotFound();
            }
            return View(curso);
        }

        //POST: CursoController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long? id)
        {
            var curso = await _context.Cursos.SingleOrDefaultAsync(m => m.CursoID == id);
            _context.Cursos.Remove(curso);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


    }
}

atividadeBDMVC/Controllers/InfraController.cs
using atividadeBDMVC.Models.Infra;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace atividadeBDMVC.Controllers
{
    [Authorize]
    public class InfraController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}

        private readonly UserManager<UsuarioDaAplicacao> _userManager;
        private readonly SignInManager<UsuarioDaAplicacao> _signInManager;
        private readonly ILogger _logger;

        public InfraController(UserManager<UsuarioDaAplicacao> userManager,
            SignInManager<UsuarioDaAplicacao> signInManager,
            ILogger<InfraController> logger)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Acessar(string returnUrl = null)
        {
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Acessar(AcessarViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Senha, model.LembrarDeMim,
               lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("Usuário Autenticado.");
                    return RedirectToLocal(returnUrl);
                }
            }
            ModelState.AddModelError(string.Empty, "Faha na tentativa de login.");
            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult RegistrarNovoUsuario(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegistrarNovoUsuario(RegistrarNovoUsuarioViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var user = new UsuarioDaAplicacao { UserName = model.Email, Email = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("Usuário criou uma nova conta com senha.");
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    _logger.LogInformation("Usuário acesso com a conta criada.");
                    return RedirectToLocal(returnUrl);
                }
                AddErrors(result);
            }
            return View(model);
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Sair()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("Usuário realizou logout.");
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

atividadeBDMVC/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<atividadeBDMVC.Models.Infra.UsuarioDaAplicacao> SignInManager
@inject Microsoft.AspNetCore.Identity.UserManager<atividadeBDMVC.Models.Infra.UsuarioDaAplicacao> UserManager

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema Escola</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="row" style="text-align:right;">
            <div class="col-6"></div>
            <div class="col-6">
                @if (SignInManager.IsSignedIn(User))
                {
                    <div>
                        Olá @UserManager.GetUserName(User), seja bem-vindo(a) / @Html.ActionLink("Logout", "Sair", "Infra", new { area = "" })
                    </div>
                }
                else
                {
                    <a class="nav-item nav-link" asp-area="" asp-controller="Infra" asp-action="Acessar">
                        Informar usuário/senha para acessar
                    </a>
                }
            </div>
        </div>



        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Departamento" asp-action="Index">Sistema Escola</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departamento" asp-action="Index">Departamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instituicao" asp-action="Index">Instituição</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso" asp-action="Index">Cursos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Disciplina" asp-action="Index">Disciplina</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CursoDisciplina" asp-action="Index">Cadastro Curso-Disciplina</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Academico" asp-action="Index">Academicos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - atividade Banco de Dados MVC
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>